export const comments = [
  {
    id: 0,
    rate: 4,
    name: "Abdullah",
    email: "abdullah@outlook.sa",
    comment: "Very nice transaction, safe and secure !",
    date: "June 21, 2020",
  },
  {
    id: 1,
    rate: 3,
    name: "Jean-Pierre",
    email: "jean-pierre@hotmail.fr",
    comment: "Was ok, try to put more information.",
    date: "June 19, 2020",
  },
  {
    id: 2,
    rate: 5,
    name: "Abid",
    email: "abid@protonmail.com",
    comment: "Thank you !",
    date: "June 18, 2020",
  },
  {
    id: 3,
    rate: 2,
    name: "Grace",
    email: "grace@etisalat.ae",
    comment: "Not happy at all, found much better with better rates",
    date: "December 6, 2019",
  },
  {
    id: 4,
    rate: 1,
    name: "Chang Lee",
    email: "chang@exemple.cn",
    comment: "Worst experience ever",
    date: "December 6, 2019",
  },
  {
    id: 5,
    rate: 5,
    name: "Samir",
    email: "samir@checkout.ae",
    comment: "Waouuuu !",
    date: "June 21, 2020",
  },
];
